USE dbDEML20240906;
GO

CREATE TABLE ProductsDEML (
    Id INT PRIMARY KEY IDENTITY(1,1),
    NombreDEML NVARCHAR(50) NOT NULL,
    DescripcionDEML NVARCHAR(200) NULL,
    Precio DECIMAL(10, 2) NOT NULL
);